name: Pylint

on:
  push:
    branches: [testing]  # only run on testing branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Run Pylint on your ETC code
      - name: Run Pylint
        run: |
          pylint etc/ --exit-zero