name: Pylint (per file)

on:
  push:
    branches: [testing]
  pull_request:
    branches: [testing]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          # - main.py
          # - services/counts.py
          - services/etc.py
          # add more as you’re ready
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install pylint
      - name: Lint ${{ matrix.file }}
        run: |
          pylint "${{ matrix.file }}" -d import-error,no-name-in-module --exit-zero